// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp2kDIMVWrpYSfABWzmWZadOV9dKLu7nE',
    appId: '1:421235763749:web:02c89c7695a2f5f7d86dcc',
    messagingSenderId: '421235763749',
    projectId: 'fruit-hup-56e92',
    authDomain: 'fruit-hup-56e92.firebaseapp.com',
    storageBucket: 'fruit-hup-56e92.firebasestorage.app',
    measurementId: 'G-V5Q888TYTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5OCWhd6AebROk_dYejGAUzRBJqABd_Bc',
    appId: '1:421235763749:android:7948233a76187c33d86dcc',
    messagingSenderId: '421235763749',
    projectId: 'fruit-hup-56e92',
    storageBucket: 'fruit-hup-56e92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQWrOYHx-7UG3_ze6Ky_iKqwHcz2MGhOA',
    appId: '1:421235763749:ios:b2be9e3741a4a8dad86dcc',
    messagingSenderId: '421235763749',
    projectId: 'fruit-hup-56e92',
    storageBucket: 'fruit-hup-56e92.firebasestorage.app',
    iosBundleId: 'com.example.fruteHup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQWrOYHx-7UG3_ze6Ky_iKqwHcz2MGhOA',
    appId: '1:421235763749:ios:b2be9e3741a4a8dad86dcc',
    messagingSenderId: '421235763749',
    projectId: 'fruit-hup-56e92',
    storageBucket: 'fruit-hup-56e92.firebasestorage.app',
    iosBundleId: 'com.example.fruteHup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp2kDIMVWrpYSfABWzmWZadOV9dKLu7nE',
    appId: '1:421235763749:web:cb82a52041bf56b9d86dcc',
    messagingSenderId: '421235763749',
    projectId: 'fruit-hup-56e92',
    authDomain: 'fruit-hup-56e92.firebaseapp.com',
    storageBucket: 'fruit-hup-56e92.firebasestorage.app',
    measurementId: 'G-MH9QLR82S4',
  );
}
